[package]
name = "basic_graph_lib"
version = "0.1.0"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "solver-cli"
path = "src/main.rs"
test = false